#Con este archivo va a declarar como y desde donde se va a iniciar el contenedor

services:       
  app-csv:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/Poblacion_Mundial

# services es una etiqueta que se va a definir
# app-csv es el nombre del servicio (puede ser cualquiera)
#build tiene un contexto que es la carpeta donde estamos ubicados (.) se hace con el punto.
#dockerfile es para definir el archivo que se va a leer, en este caso Dokerfile
#volumes se encarga de enlazar los archivos al contenedor para que se actualicen sin necesidad de reconstruir el contenedor

#Finalmente se lee de la siguiente manera: "contruye un servicio que esta ubicado en la carpeta (contexto) Dokerfile"